# Generated by Django 3.2.7 on 2021-10-31 17:50

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_video_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='content_video_url',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
