# Generated by Django 3.2.7 on 2021-10-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20211031_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_video_title',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
