# Generated by Django 3.2.7 on 2021-11-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_video_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
