# Generated by Django 3.2.7 on 2021-11-01 06:16

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20211101_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
