# Generated by Django 3.2.7 on 2021-11-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_video_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
