# Generated by Django 3.2.7 on 2021-11-01 06:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_after',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', null=True),
        ),
    ]
